import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Bugpilot } from "@bugpilot/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Bugpilot
          workspaceId="workspace-4848edc7-365c-40a9-8c77-fa19217047f8"
          user={null}
          enabled={true}
        >
          {children}
        </Bugpilot>
      </body>
    </html>
  );
}
